# Generated by Django 5.2 on 2025-05-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0003_customuser_age_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
