# Generated by Django 5.2 on 2025-05-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0004_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
