# Generated by Django 5.2 on 2025-05-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0005_alter_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
