# Generated by Django 5.2 on 2025-05-20 07:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('ml', 'Machine Learning'), ('dl', 'Deep Learning'), ('ai', 'Artificial Intelligence'), ('ai_pop_culture', 'AI in pop-culture'), ('ai_application', 'Application of AI'), ('cv', 'Computer Vision'), ('nlp', 'Natural Language Processing'), ('gen_ai', 'Generative AI'), ('ststs', 'Statistics')], max_length=240, verbose_name='Topic')),
                ('question_name', models.TextField(verbose_name='Question')),
                ('answer_choices', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=4, verbose_name='Answer Choices')),
                ('true_answer_indexes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='Indices of Correct Answers')),
                ('difficulty', models.TextField(choices=[('beginner', 'Beginner Level'), ('moderate', 'Moderate Level'), ('advanced', 'Advanced Level')], max_length=100, verbose_name='question difficulty')),
                ('question_xp', models.PositiveIntegerField(blank=True, verbose_name='XP')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuizGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answers', models.JSONField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_game.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('total_correct_answers', models.PositiveIntegerField(default=0)),
                ('knowledge_level', models.CharField(choices=[('beginner', 'Beginner Level'), ('moderate', 'Moderate Level'), ('advanced', 'Advanced Level')], default='beginner', max_length=20, verbose_name='Knowledge Level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
